### ISSUE TITLE
Freitagsfoo wird an Samstagen mit angezeigt

### ISSUE THREAD

**Issue by nomaster** [chaosdorf/wikicron#3]
Weil der Freitagsfoo eine Dauer von 8 Stunden eingetragen hat, lappt der Termin in den Samstag über und wird auch für diesen Tag im Kalender eingetragen. Das ist unübersichtlich. Daher schlage ich vor, wir setzen die Dauer auf 6 Stunden - also bis 24 Uhr.

Betreffende Zeile:
https://github.com/chaosdorf/wikicron/blob/599fc832817216f99e1c47e065fa465bd67e0a00/extern/freitagsfoo#L37

**Comment by derf** [comment]
Bezieht sich das auf Kalender allgemein oder [https://wiki.chaosdorf.de/Chaosdorf_Wiki:Current_events](den Wikikalender)? Falls letzteres würde den anpassen, so dass überlappende Termine ignoriert werden, wenn sie vor 8 Uhr morgens enden.
